import os
import subprocess
import datetime
import re

def main():
    # 생성할 헤더 파일 경로 (Core/Inc/version.h)
    output_path = os.path.join("Core", "Inc", "version.h")
    
    # 1. Git 정보 가져오기
    try:
        # 예: v1.0.0-4-g9a2b-dirty (태그-커밋수-해시-변경사항유무)
        version_str = subprocess.check_output(
            ["git", "describe", "--tags", "--always", "--dirty"], 
            stderr=subprocess.DEVNULL
        ).decode().strip()
    except:
        version_str = "v0.0.0-unknown"
        
    try:
        # 커밋 해시 (예: 9a2b3c)
        commit_hash = subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"], 
            stderr=subprocess.DEVNULL
        ).decode().strip()
    except:
        commit_hash = "unknown"
        
    build_date = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # 2. Semantic Versioning 파싱 (Major.Minor.Patch)
    # 예: v1.0.2-4-g9a2b -> Major:1, Minor:0, Patch:2
    match = re.search(r"v?(\d+)\.(\d+)\.(\d+)", version_str)
    if match:
        major, minor, patch = match.groups()
    else:
        # 태그가 없거나 형식이 맞지 않으면 0.0.0으로 처리
        major, minor, patch = ("0", "0", "0")

    # 3. 헤더 파일 내용 작성
    header_content = f"""#ifndef VERSION_H
#define VERSION_H

// Auto-generated by generate_version.py
#define FW_VERSION_STRING   "{version_str}"
#define FW_MAJOR_VERSION    {major}
#define FW_MINOR_VERSION    {minor}
#define FW_PATCH_VERSION    {patch}

#define FW_COMMIT_HASH      "{commit_hash}"
#define FW_BUILD_DATE       "{build_date}"

#endif // VERSION_H
"""

    # 4. 파일 쓰기
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(header_content)
        
if __name__ == "__main__":
    main()