import datetime
import os
import re
import subprocess


def run_git(args):
    try:
        result = subprocess.run(
            ["git"] + args,
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode != 0:
            return None
        return result.stdout.strip()
    except Exception:
        return None


def is_dirty():
    try:
        worktree = subprocess.run(
            ["git", "diff", "--quiet"],
            check=False,
        ).returncode
        staged = subprocess.run(
            ["git", "diff", "--cached", "--quiet"],
            check=False,
        ).returncode
        return worktree == 1 or staged == 1
    except Exception:
        return False


def main():
    output_path = os.path.join("Core", "Inc", "version.h")

    tag = run_git(["describe", "--tags", "--abbrev=0"]) or "v0.0.0"
    commit_hash = run_git(["rev-parse", "--short", "HEAD"]) or "unknown"
    branch = run_git(["rev-parse", "--abbrev-ref", "HEAD"]) or "unknown"
    dirty_flag = "-dirty" if is_dirty() else ""

    match = re.search(r"v?(\d+)\.(\d+)\.(\d+)", tag)
    if match:
        major, minor, patch = match.groups()
    else:
        major, minor, patch = ("0", "0", "0")
        tag = "v0.0.0"

    now = datetime.datetime.now()
    build_date = now.strftime("%Y-%m-%d")
    build_time = now.strftime("%H:%M:%S")

    header_content = f"""#ifndef VERSION_H
#define VERSION_H

// Auto-generated by generate_version.py
#define FW_VERSION_STRING   "{tag}{dirty_flag}"
#define FW_MAJOR_VERSION    {major}
#define FW_MINOR_VERSION    {minor}
#define FW_PATCH_VERSION    {patch}

#define FW_BUILD_DATE       "{build_date}"
#define FW_BUILD_TIME       "{build_time}"
#define GIT_COMMIT_HASH     "{commit_hash}{dirty_flag}"
#define GIT_BRANCH          "{branch}"
#define GIT_TAG             "{tag}"
#define FW_VERSION_INFO     FW_VERSION_STRING " (" GIT_COMMIT_HASH ")"

#endif // VERSION_H
"""

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(header_content)


if __name__ == "__main__":
    main()
