#!/usr/bin/env python3
"""
IAR Prebuild Script: Auto-generate version.h
Extracts Git information and creates version header file
"""

import subprocess
import datetime
import os
import sys

def run_git_command(cmd):
    """Run git command and return output"""
    try:
        result = subprocess.run(
            cmd,
            shell=True,
            capture_output=True,
            text=True,
            cwd=os.path.dirname(os.path.dirname(__file__))
        )
        return result.stdout.strip() if result.returncode == 0 else ""
    except Exception as e:
        print(f"Error running git command: {e}")
        return ""

def run_git_returncode(cmd):
    """Run git command and return exit code (or None on execution error)."""
    try:
        result = subprocess.run(
            cmd,
            shell=True,
            capture_output=True,
            text=True,
            cwd=os.path.dirname(os.path.dirname(__file__))
        )
        return result.returncode
    except Exception:
        return None

def get_git_info():
    """Get Git information"""
    worktree_diff = run_git_returncode('git diff --quiet')
    staged_diff = run_git_returncode('git diff --cached --quiet')

    info = {
        'hash': run_git_command('git rev-parse --short HEAD'),
        'branch': run_git_command('git rev-parse --abbrev-ref HEAD'),
        'tag': run_git_command('git describe --tags --abbrev=0'),
        'dirty': (worktree_diff == 1) or (staged_diff == 1)
    }

    # Default version if no tag exists
    if not info['tag']:
        info['tag'] = 'v0.0.0'

    # Parse version (v1.2.3 -> [1, 2, 3])
    version_str = info['tag'].lstrip('v')
    try:
        parts = version_str.split('.')
        info['major'] = int(parts[0]) if len(parts) > 0 else 0
        info['minor'] = int(parts[1]) if len(parts) > 1 else 0
        info['patch'] = int(parts[2]) if len(parts) > 2 else 0
    except (ValueError, IndexError):
        info['major'] = info['minor'] = info['patch'] = 0

    return info

def generate_version_header(git_info):
    """Generate version.h file content"""
    now = datetime.datetime.now()
    dirty_flag = '-dirty' if git_info['dirty'] else ''

    content = f"""#ifndef VERSION_H
#define VERSION_H

// Auto-generated by prebuild script - DO NOT EDIT MANUALLY
// Generated on: {now.strftime('%Y-%m-%d %H:%M:%S')}

// Firmware Version
#define FW_MAJOR_VERSION    {git_info['major']}
#define FW_MINOR_VERSION    {git_info['minor']}
#define FW_PATCH_VERSION    {git_info['patch']}

// Version String
#define FW_VERSION_STRING   "{git_info['tag']}{dirty_flag}"

// Build Information
#define FW_BUILD_DATE       "{now.strftime('%Y-%m-%d')}"
#define FW_BUILD_TIME       "{now.strftime('%H:%M:%S')}"
#define FW_BUILD_TIMESTAMP  {int(now.timestamp())}

// Git Information
#define GIT_COMMIT_HASH     "{git_info['hash']}{dirty_flag}"
#define GIT_BRANCH          "{git_info['branch']}"
#define GIT_TAG             "{git_info['tag']}"

// Helper macros
#define FW_VERSION_FULL     "{git_info['major']}.{git_info['minor']}.{git_info['patch']}"
#define FW_VERSION_INFO     FW_VERSION_STRING " (" GIT_COMMIT_HASH ")"

#endif // VERSION_H
"""
    return content

def main():
    """Main function"""
    # Get project root directory
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    version_h_path = os.path.join(project_root, 'Core', 'Inc', 'version.h')

    print("Generating version.h...")

    # Get Git information
    git_info = get_git_info()

    print(f"Version: {git_info['tag']}")
    print(f"Commit: {git_info['hash']}")
    print(f"Branch: {git_info['branch']}")
    print(f"Dirty: {'Yes' if git_info['dirty'] else 'No'}")

    # Generate header content
    content = generate_version_header(git_info)

    # Write to file
    try:
        os.makedirs(os.path.dirname(version_h_path), exist_ok=True)
        with open(version_h_path, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"version.h generated successfully at: {version_h_path}")
        return 0
    except Exception as e:
        print(f"Error writing version.h: {e}", file=sys.stderr)
        return 1

if __name__ == '__main__':
    sys.exit(main())
