@echo off
REM ============================================
REM IAR Prebuild Script: Auto-generate version.h
REM ============================================

setlocal enabledelayedexpansion

REM Get Git information
for /f "tokens=*" %%i in ('git rev-parse --short HEAD 2^>nul') do set GIT_HASH=%%i
for /f "tokens=*" %%i in ('git rev-parse --abbrev-ref HEAD 2^>nul') do set GIT_BRANCH=%%i
for /f "tokens=*" %%i in ('git describe --tags --abbrev=0 2^>nul') do set GIT_TAG=%%i

REM If no tag exists, use default version
if "%GIT_TAG%"=="" set GIT_TAG=v0.0.0

REM Parse version from tag (v1.2.3 -> 1 2 3)
set VERSION_STRING=%GIT_TAG:~1%
for /f "tokens=1,2,3 delims=." %%a in ("%VERSION_STRING%") do (
    set MAJOR=%%a
    set MINOR=%%b
    set PATCH=%%c
)

REM Get build date and time
for /f "tokens=1-3 delims=/ " %%a in ('date /t') do set BUILD_DATE=%%a-%%b-%%c
for /f "tokens=1-2 delims=: " %%a in ('time /t') do set BUILD_TIME=%%a:%%b

REM Get dirty status (uncommitted changes)
git diff --quiet 2>nul
if errorlevel 1 (
    set DIRTY_FLAG=-dirty
) else (
    set DIRTY_FLAG=
)

REM Generate version.h file
echo Generating version.h...
echo #ifndef VERSION_H > Core\Inc\version.h
echo #define VERSION_H >> Core\Inc\version.h
echo. >> Core\Inc\version.h
echo // Auto-generated by prebuild script - DO NOT EDIT MANUALLY >> Core\Inc\version.h
echo // Generated on: %date% %time% >> Core\Inc\version.h
echo. >> Core\Inc\version.h
echo // Firmware Version >> Core\Inc\version.h
echo #define FW_MAJOR_VERSION    %MAJOR% >> Core\Inc\version.h
echo #define FW_MINOR_VERSION    %MINOR% >> Core\Inc\version.h
echo #define FW_PATCH_VERSION    %PATCH% >> Core\Inc\version.h
echo. >> Core\Inc\version.h
echo // Version String >> Core\Inc\version.h
echo #define FW_VERSION_STRING   "%GIT_TAG%%DIRTY_FLAG%" >> Core\Inc\version.h
echo. >> Core\Inc\version.h
echo // Build Information >> Core\Inc\version.h
echo #define FW_BUILD_DATE       "%BUILD_DATE%" >> Core\Inc\version.h
echo #define FW_BUILD_TIME       "%BUILD_TIME%" >> Core\Inc\version.h
echo. >> Core\Inc\version.h
echo // Git Information >> Core\Inc\version.h
echo #define GIT_COMMIT_HASH     "%GIT_HASH%%DIRTY_FLAG%" >> Core\Inc\version.h
echo #define GIT_BRANCH          "%GIT_BRANCH%" >> Core\Inc\version.h
echo #define GIT_TAG             "%GIT_TAG%" >> Core\Inc\version.h
echo. >> Core\Inc\version.h
echo #endif // VERSION_H >> Core\Inc\version.h

echo version.h generated successfully!
echo Version: %GIT_TAG% (commit: %GIT_HASH%)
exit /b 0
