param(
    [string]$OutputHeader = "..\Core\Inc\version.h",
    [string]$FallbackVersion = "0.0.0"
)

$ErrorActionPreference = "Stop"

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = (Resolve-Path (Join-Path $scriptDir "..")).Path
$headerPath = Join-Path $scriptDir $OutputHeader
$headerDir = Split-Path -Parent $headerPath
$gitExe = (Get-Command git -ErrorAction SilentlyContinue | Select-Object -First 1 -ExpandProperty Source)

if (-not (Test-Path $headerDir)) {
    New-Item -ItemType Directory -Path $headerDir -Force | Out-Null
}

function Invoke-Git {
    param([string[]]$GitArgs)
    if ([string]::IsNullOrWhiteSpace($gitExe)) { return $null }
    try {
        $result = & $gitExe -C $repoRoot @GitArgs 2>$null
        if ($LASTEXITCODE -ne 0) { return $null }
        return ($result -join "`n").Trim()
    } catch {
        return $null
    }
}

$shortHash = Invoke-Git -GitArgs @("rev-parse", "--short", "HEAD")
if ([string]::IsNullOrWhiteSpace($shortHash)) { $shortHash = "unknown" }

$branch = Invoke-Git -GitArgs @("rev-parse", "--abbrev-ref", "HEAD")
if ([string]::IsNullOrWhiteSpace($branch)) { $branch = "unknown" }

$exactTag = Invoke-Git -GitArgs @("describe", "--tags", "--exact-match")
$latestTag = Invoke-Git -GitArgs @("describe", "--tags", "--abbrev=0")

$rawTag = if (-not [string]::IsNullOrWhiteSpace($exactTag)) { $exactTag } else { $latestTag }
if ([string]::IsNullOrWhiteSpace($rawTag)) { $rawTag = "v$FallbackVersion" }

$status = Invoke-Git -GitArgs @("status", "--porcelain")
$dirtyFlag = if ([string]::IsNullOrWhiteSpace($status)) { "" } else { "-dirty" }

$versionText = $rawTag.Trim()
if ($versionText.StartsWith("v")) {
    $versionText = $versionText.Substring(1)
}

$versionMatch = [regex]::Match($versionText, "^(\d+)\.(\d+)\.(\d+)$")
if (-not $versionMatch.Success) {
    $versionText = $FallbackVersion
    $versionMatch = [regex]::Match($versionText, "^(\d+)\.(\d+)\.(\d+)$")
}

$major = $versionMatch.Groups[1].Value
$minor = $versionMatch.Groups[2].Value
$patch = $versionMatch.Groups[3].Value
$gitTag = "v$versionText"
$generatedOn = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")

$content = @"
#ifndef VERSION_H
#define VERSION_H

// Auto-generated by EWARM/prebuild_version.ps1 - DO NOT EDIT MANUALLY
// Generated on: $generatedOn

// Firmware Version
#define FW_MAJOR_VERSION    $major
#define FW_MINOR_VERSION    $minor
#define FW_PATCH_VERSION    $patch

// Version String
#define FW_VERSION_STRING   "$gitTag"

// Build Information
#define FW_BUILD_DATE       __DATE__
#define FW_BUILD_TIME       __TIME__

// Git Information
#define GIT_COMMIT_HASH     "$shortHash$dirtyFlag"
#define GIT_BRANCH          "$branch"
#define GIT_TAG             "$gitTag"

// Helper macros
#define FW_VERSION_FULL     "$versionText"
#define FW_VERSION_INFO     FW_VERSION_STRING " (" GIT_COMMIT_HASH ")"

#endif // VERSION_H
"@

$existing = if (Test-Path $headerPath) { Get-Content -Path $headerPath -Raw } else { "" }
if ($existing -ne $content) {
    Set-Content -Path $headerPath -Value $content -Encoding ascii
    Write-Host "Updated: $headerPath"
} else {
    Write-Host "No changes: $headerPath"
}
